name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
        - main

jobs:
  run-action:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prettier check
        run: npm run prettier:check

      - name: Start MongoDB
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.testing.yml"

      - name: Tests
        run: npm run test